### ISSUE TITLE
way to thread safe write

### ISSUE THREAD

**Issue by olaulau** [Wruczek/PHP-File-Cache#2]
is there a way to ensure concurrent write (store) into a single cache file ?

**Comment by Wruczek** [comment]
Not without modifications of PHP-File-Cache. Sadly, Im not experienced with threading in PHP.

**Comment by olaulau** [comment]
I don't use PHP-threads either, because they are not trivial to install and not available everywhere.
so I use fork processes, i.e. PHP CLI scripts launched with popen(), and waiting for their completion with pclose(). in those scripts, I write to the cache (if needed) with store() method. when my scripts execute very fast, I encounter write race condition with some data not being written (maybe overwritten by other process).
I'm looking for other solutions, one file-based with file lock, other with sqlite db.

**Comment by Wruczek** [comment]
Yep, in that case the data is overwritten by other processes. If you dont need a shared cache, having a separate cache names for different processes might work, because they are stored in separate files
```php
$cache = new PhpFileCache("/cache/folder", "process1");
```

**Comment by olaulau** [comment]
of course, but it's not my use case. thanks !

**Comment by olaulau** [comment]
do you accept contributions ? are you interested in a MR which solves this problem ?

**Comment by Wruczek** [comment]
Sure!

**Comment by olaulau** [comment]
i've made some bench with locking, sqlite perfs are very poor. so I will stay with simple files.
